apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-backend
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/spinnsyn-backend
        mountPath: /secrets/azuread/spinnsyn-backend
      - kvPath: serviceuser/data/dev/srvspinnsyn
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/spinnsyn-backend/default
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://spinnsyn-backend.nais.preprod.local"
  webproxy: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SPINNSYN_BACKEND_DB_URL
      value: jdbc:postgresql://b27dbvl015.preprod.local:5432/spinnsyn-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
