apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: spinnsyn-db
            diskAutoresize: true
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: api-gw-q1.oera.no
        - host: navtestb2c.b2clogin.com
    inbound:
      rules:
        - application: spinnsyn-backend-proxy
        - application: spinnsyn-backend-veileder-proxy
        - application: spinnsyn-backend-mock-proxy # Kun i dev-gcp

  envFrom:
    - secret: spinnsyn-backend-serviceuser
    - secret: syfo-tilgangskontroll-spinnsyn-backend-api-gw-key
    - configmap: loginservice-idporten
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SPINNSYN_FRONTEND_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepenger"
    - name: VEILEDER_WELLKNOWN_URI
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration"
    - name: VEILEDER_EXPECTED_AUDIENCE
      value: "38e07d31-659d-4595-939a-f18dce3446c5,281ba984-745f-48b8-a79c-9444b8688361"
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais-q.adeo.no
    - name: API_GATEWAY_URL
      value: https://api-gw-q1.oera.no
